language: node_js

notifications:
  email: false

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - make install

script:
    - make test
after_success:
    - npm run report-codecov
